spring:
  profiles:
    active: dev

opencageapi:
  endpoint: https://api.opencagedata.com/geocode/v1/json?key=5a2b4cfb21d44b94a7ce45110cf1233d&q=

jwt:
  header: Authorization
  secret: rvtsecret

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3308/revtaroom
    username: iago
    password: P@ssw0rd
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
